title: Latent Variable Sequential Set Transformers For Joint Multi-Agent Motion Prediction
description: Presenting a novel architecture for sequence-modelling of sets<br>@Roger add the list of authors here pls
theme: jekyll-theme-cayman
